#!/usr/bin/env python3
"""
Build chart_catalog.json from the Apache ECharts Excel workbook.
Run: python scripts/build_catalog.py
Output: backend/catalog/chart_catalog.json
"""
import json
import os
import sys
from pathlib import Path

import openpyxl

ROOT = Path(__file__).parent.parent
XLSX_PATH = ROOT / "apache_echarts_chart_catalog_final.xlsx"
OUTPUT_PATH = ROOT / "backend" / "catalog" / "chart_catalog.json"

# ---------------------------------------------------------------------------
# Mapping: sheet name → category slug
# ---------------------------------------------------------------------------
SHEET_CATEGORY_MAP = {
    "Bar Charts": "bar",
    "Line Charts": "line",
    "Pie  Charts": "pie",
    "Scatter Charts": "scatter",
    "Map": "map",
    "Candlestick Charts": "candlestick",
    "Radar Charts": "radar",
    "Box plot charts ": "boxplot",
    "Custom Charts": "custom",
    "Heatmap": "heatmap",
    "Graph": "graph",
    "Tree": "tree",
    "Treemap": "treemap",
    "Sunburst": "sunburst",
    "Calendar": "calendar",
    "Matrix": "matrix",
    "Chord": "chord",
    "Parallel charts": "parallel",
    "Sankey Charts": "sankey",
    "Funnel Charts": "funnel",
    "Gauge": "gauge",
    "Theme River": "themeriver",
    "Table": "table",
    "KPI": "kpi",
    "3D Charts": "3d",
}

# ---------------------------------------------------------------------------
# Per-chart metadata: data requirements, echarts type, scoring hints
# ---------------------------------------------------------------------------
CHART_META = {
    # ── Bar ──────────────────────────────────────────────────────────────────
    "bar": {
        "id": "bar",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": ["series_categorical"],
        "min_cols": 2,
        "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False,
        "requires_3d": False,
        "requires_flow": False,
        "requires_hierarchy": False,
        "requires_ohlc": False,
        "webgl": False,
        "max_categories_ideal": 20,
        "mapping_keys": ["x", "y"],
        "scoring_hints": {"time_series_bonus": 0, "category_metric_bonus": 20},
    },
    "waterfall_chart": {
        "id": "waterfall_chart",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2,
        "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 15,
        "mapping_keys": ["category", "value"],
        "scoring_hints": {"ordered_category_bonus": 15},
    },
    "polar_bar": {
        "id": "polar_bar",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 12,
        "mapping_keys": ["angle", "value"],
        "scoring_hints": {},
    },
    "bar_chart_race": {
        "id": "bar_chart_race",
        "echarts_type": "bar",
        "required_semantics": ["datetime", "categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 20,
        "mapping_keys": ["time", "category", "value"],
        "scoring_hints": {"time_series_bonus": 15},
    },
    "range_bar_chart": {
        "id": "range_bar_chart",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 15,
        "mapping_keys": ["category", "low", "high"],
        "scoring_hints": {"two_numeric_bonus": 10},
    },
    "horizontal_waterfall_chart": {
        "id": "horizontal_waterfall_chart",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 15,
        "mapping_keys": ["category", "value"],
        "scoring_hints": {},
    },
    "circular_bar_chart": {
        "id": "circular_bar_chart",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 12,
        "mapping_keys": ["category", "value"],
        "scoring_hints": {},
    },
    "stacked_bar_chart": {
        "id": "stacked_bar_chart",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric", "series"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 20,
        "mapping_keys": ["x", "series", "value"],
        "scoring_hints": {"multi_categorical_bonus": 15},
    },
    "3d_bar_chart": {
        "id": "3d_bar_chart",
        "echarts_type": "bar3D",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": ["categorical"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": True, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 20,
        "mapping_keys": ["x", "y", "value"],
        "scoring_hints": {"multi_categorical_bonus": 10},
    },
    "progress_bar": {
        "id": "progress_bar",
        "echarts_type": "bar",
        "required_semantics": ["numeric"],
        "optional_semantics": ["numeric"],
        "min_cols": 1, "max_cols": 3,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 1,
        "mapping_keys": ["value", "target"],
        "scoring_hints": {"single_numeric_bonus": 10},
    },
    "bar_with_line": {
        "id": "bar_with_line",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 20,
        "mapping_keys": ["x", "bar_value", "line_value"],
        "scoring_hints": {"two_numeric_bonus": 15},
    },
    "error_bar_chart": {
        "id": "error_bar_chart",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 15,
        "mapping_keys": ["category", "value", "error"],
        "scoring_hints": {},
    },
    "stacked_horizontal_bar": {
        "id": "stacked_horizontal_bar",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric", "series"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 20,
        "mapping_keys": ["y", "series", "value"],
        "scoring_hints": {"multi_categorical_bonus": 15},
    },
    "horizontal_bar": {
        "id": "horizontal_bar",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 25,
        "mapping_keys": ["y", "x"],
        "scoring_hints": {"category_metric_bonus": 15},
    },
    "100_stacked_bar": {
        "id": "100_stacked_bar",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric", "series"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 20,
        "mapping_keys": ["x", "series", "value"],
        "scoring_hints": {"multi_categorical_bonus": 10},
    },
    "100_stacked_horizontal_bar": {
        "id": "100_stacked_horizontal_bar",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric", "series"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 20,
        "mapping_keys": ["y", "series", "value"],
        "scoring_hints": {"multi_categorical_bonus": 10},
    },
    "pictorial_bar": {
        "id": "pictorial_bar",
        "echarts_type": "pictorialBar",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 10,
        "mapping_keys": ["x", "y"],
        "scoring_hints": {},
    },
    "polar_end_angle_arc_bar": {
        "id": "polar_end_angle_arc_bar",
        "echarts_type": "bar",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 8,
        "mapping_keys": ["category", "value"],
        "scoring_hints": {},
    },
    # ── Line ─────────────────────────────────────────────────────────────────
    "line": {
        "id": "line",
        "echarts_type": "line",
        "required_semantics": ["datetime_or_ordered", "numeric"],
        "optional_semantics": ["series_categorical"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y"],
        "scoring_hints": {"time_series_bonus": 25},
    },
    "area": {
        "id": "area",
        "echarts_type": "line",
        "required_semantics": ["datetime_or_ordered", "numeric"],
        "optional_semantics": ["series_categorical"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y"],
        "scoring_hints": {"time_series_bonus": 20},
    },
    "stepped_line": {
        "id": "stepped_line",
        "echarts_type": "line",
        "required_semantics": ["datetime_or_ordered", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y"],
        "scoring_hints": {"time_series_bonus": 15},
    },
    "smooth_line": {
        "id": "smooth_line",
        "echarts_type": "line",
        "required_semantics": ["datetime_or_ordered", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y"],
        "scoring_hints": {"time_series_bonus": 15},
    },
    "polar_line": {
        "id": "polar_line",
        "echarts_type": "line",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 12,
        "mapping_keys": ["angle", "value"],
        "scoring_hints": {},
    },
    "stacked_area": {
        "id": "stacked_area",
        "echarts_type": "line",
        "required_semantics": ["datetime_or_ordered", "numeric", "series"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "series", "y"],
        "scoring_hints": {"time_series_bonus": 15, "multi_categorical_bonus": 10},
    },
    "3d_line_chart": {
        "id": "3d_line_chart",
        "echarts_type": "line3D",
        "required_semantics": ["numeric", "numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": True, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y", "z"],
        "scoring_hints": {"three_numeric_bonus": 15},
    },
    "stacked_line_chart": {
        "id": "stacked_line_chart",
        "echarts_type": "line",
        "required_semantics": ["datetime_or_ordered", "numeric", "series"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "series", "y"],
        "scoring_hints": {"time_series_bonus": 10, "multi_categorical_bonus": 10},
    },
    "bump_chart": {
        "id": "bump_chart",
        "echarts_type": "line",
        "required_semantics": ["datetime", "categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 15,
        "mapping_keys": ["time", "category", "rank"],
        "scoring_hints": {"time_series_bonus": 10},
    },
    "confidence_band_line": {
        "id": "confidence_band_line",
        "echarts_type": "line",
        "required_semantics": ["datetime_or_ordered", "numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "value", "lower", "upper"],
        "scoring_hints": {},
    },
    "function_plot": {
        "id": "function_plot",
        "echarts_type": "line",
        "required_semantics": ["numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": 2,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y"],
        "scoring_hints": {},
    },
    "multi_x_axis_line": {
        "id": "multi_x_axis_line",
        "echarts_type": "line",
        "required_semantics": ["datetime_or_ordered", "numeric"],
        "optional_semantics": ["numeric"],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y1", "y2"],
        "scoring_hints": {"time_series_bonus": 10},
    },
    # ── Pie ──────────────────────────────────────────────────────────────────
    "pie": {
        "id": "pie",
        "echarts_type": "pie",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": 2,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 7,
        "mapping_keys": ["name", "value"],
        "scoring_hints": {"category_metric_bonus": 15, "pie_cardinality_penalty": True},
    },
    "donut": {
        "id": "donut",
        "echarts_type": "pie",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": 2,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 7,
        "mapping_keys": ["name", "value"],
        "scoring_hints": {"category_metric_bonus": 15, "pie_cardinality_penalty": True},
    },
    "nightingale_rose": {
        "id": "nightingale_rose",
        "echarts_type": "pie",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": 2,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 10,
        "mapping_keys": ["name", "value"],
        "scoring_hints": {"category_metric_bonus": 10, "pie_cardinality_penalty": True},
    },
    # ── Scatter ───────────────────────────────────────────────────────────────
    "scatter": {
        "id": "scatter",
        "echarts_type": "scatter",
        "required_semantics": ["numeric", "numeric"],
        "optional_semantics": ["categorical", "numeric"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y"],
        "scoring_hints": {"two_numeric_bonus": 25},
    },
    "bubble": {
        "id": "bubble",
        "echarts_type": "scatter",
        "required_semantics": ["numeric", "numeric", "numeric"],
        "optional_semantics": ["categorical"],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y", "size"],
        "scoring_hints": {"three_numeric_bonus": 20},
    },
    "effect_scatter": {
        "id": "effect_scatter",
        "echarts_type": "effectScatter",
        "required_semantics": ["numeric", "numeric"],
        "optional_semantics": ["numeric", "categorical"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y"],
        "scoring_hints": {"two_numeric_bonus": 15},
    },
    "scatter_matrix": {
        "id": "scatter_matrix",
        "echarts_type": "scatter",
        "required_semantics": ["numeric", "numeric", "numeric"],
        "optional_semantics": ["categorical"],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["dimensions"],
        "scoring_hints": {"many_numeric_bonus": 20},
    },
    "3d_scatter_plot": {
        "id": "3d_scatter_plot",
        "echarts_type": "scatter3D",
        "required_semantics": ["numeric", "numeric", "numeric"],
        "optional_semantics": ["categorical"],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": True, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y", "z"],
        "scoring_hints": {"three_numeric_bonus": 20},
    },
    # ── Map ──────────────────────────────────────────────────────────────────
    "geographic_region_map": {
        "id": "geographic_region_map",
        "echarts_type": "map",
        "required_semantics": ["geo_named", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": True},
        "requires_geo": True, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["region", "value"],
        "scoring_hints": {"geo_named_bonus": 30},
    },
    "geo_connection_lines": {
        "id": "geo_connection_lines",
        "echarts_type": "lines",
        "required_semantics": ["geo_lat", "geo_lon", "geo_lat", "geo_lon"],
        "optional_semantics": ["numeric"],
        "min_cols": 4, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": True},
        "requires_geo": True, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["src_lat", "src_lon", "dst_lat", "dst_lon", "value"],
        "scoring_hints": {"geo_latlon_bonus": 25},
    },
    "3d_geographic_globe": {
        "id": "3d_geographic_globe",
        "echarts_type": "globe",
        "required_semantics": ["geo_lat", "geo_lon"],
        "optional_semantics": ["numeric"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": True},
        "requires_geo": True, "requires_3d": True, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["latitude", "longitude", "value"],
        "scoring_hints": {"geo_latlon_bonus": 20},
    },
    "3d_arc_map": {
        "id": "3d_arc_map",
        "echarts_type": "lines3D",
        "required_semantics": ["geo_lat", "geo_lon", "geo_lat", "geo_lon"],
        "optional_semantics": ["numeric"],
        "min_cols": 4, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": True},
        "requires_geo": True, "requires_3d": True, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["src_lat", "src_lon", "dst_lat", "dst_lon"],
        "scoring_hints": {"geo_latlon_bonus": 20},
    },
    "3d_scatter_map": {
        "id": "3d_scatter_map",
        "echarts_type": "scatter3D",
        "required_semantics": ["geo_lat", "geo_lon", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": True},
        "requires_geo": True, "requires_3d": True, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["longitude", "latitude", "value"],
        "scoring_hints": {"geo_latlon_bonus": 25},
    },
    "heatmap_geo": {
        "id": "heatmap_geo",
        "echarts_type": "heatmap",
        "required_semantics": ["geo_lat", "geo_lon", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": True},
        "requires_geo": True, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["latitude", "longitude", "value"],
        "scoring_hints": {"geo_latlon_bonus": 20},
    },
    "3d_grid_map": {
        "id": "3d_grid_map",
        "echarts_type": "bar3D",
        "required_semantics": ["geo_lat", "geo_lon", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": True},
        "requires_geo": True, "requires_3d": True, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y", "value"],
        "scoring_hints": {"geo_latlon_bonus": 15},
    },
    "screen_grid_map": {
        "id": "screen_grid_map",
        "echarts_type": "heatmap",
        "required_semantics": ["numeric", "numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": True},
        "requires_geo": True, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y", "value"],
        "scoring_hints": {"geo_latlon_bonus": 10},
    },
    "contour_map": {
        "id": "contour_map",
        "echarts_type": "custom",
        "required_semantics": ["numeric", "numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": True},
        "requires_geo": True, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y", "z"],
        "scoring_hints": {"geo_latlon_bonus": 10, "three_numeric_bonus": 10},
    },
    "deck_multilayer_map": {
        "id": "deck_multilayer_map",
        "echarts_type": "custom",
        "required_semantics": ["geo_lat", "geo_lon"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": True},
        "requires_geo": True, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["latitude", "longitude"],
        "scoring_hints": {"geo_latlon_bonus": 15},
    },
    "3d_geo_arcs": {
        "id": "3d_geo_arcs",
        "echarts_type": "lines3D",
        "required_semantics": ["geo_lat", "geo_lon", "geo_lat", "geo_lon", "numeric"],
        "optional_semantics": [],
        "min_cols": 5, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": True},
        "requires_geo": True, "requires_3d": True, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["src_lat", "src_lon", "dst_lat", "dst_lon", "value"],
        "scoring_hints": {"geo_latlon_bonus": 15},
    },
    # ── Candlestick ───────────────────────────────────────────────────────────
    "candlestick_chart": {
        "id": "candlestick_chart",
        "echarts_type": "candlestick",
        "required_semantics": ["datetime", "numeric", "numeric", "numeric", "numeric"],
        "optional_semantics": ["numeric"],
        "min_cols": 5, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": True, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["date", "open", "close", "low", "high"],
        "scoring_hints": {"ohlc_bonus": 40},
    },
    # ── Radar ─────────────────────────────────────────────────────────────────
    "radar": {
        "id": "radar",
        "echarts_type": "radar",
        "required_semantics": ["categorical", "numeric", "numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 4, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["series", "dimensions"],
        "scoring_hints": {"many_numeric_bonus": 15},
    },
    # ── Box Plot ──────────────────────────────────────────────────────────────
    "box_plot": {
        "id": "box_plot",
        "echarts_type": "boxplot",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 15,
        "mapping_keys": ["category", "values"],
        "scoring_hints": {"category_metric_bonus": 10},
    },
    # ── Custom / Bullet ───────────────────────────────────────────────────────
    "bullet_chart": {
        "id": "bullet_chart",
        "echarts_type": "custom",
        "required_semantics": ["numeric"],
        "optional_semantics": ["numeric"],
        "min_cols": 1, "max_cols": 3,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["actual", "target"],
        "scoring_hints": {"single_numeric_bonus": 10},
    },
    # ── Heatmap ───────────────────────────────────────────────────────────────
    "heatmap": {
        "id": "heatmap",
        "echarts_type": "heatmap",
        "required_semantics": ["categorical", "categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y", "value"],
        "scoring_hints": {"multi_categorical_bonus": 20},
    },
    "calendar_heatmap": {
        "id": "calendar_heatmap",
        "echarts_type": "heatmap",
        "required_semantics": ["datetime", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": 2,
        "supports": {"numeric": True, "categorical": False, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["date", "value"],
        "scoring_hints": {"time_series_bonus": 20},
    },
    "polar_heatmap": {
        "id": "polar_heatmap",
        "echarts_type": "heatmap",
        "required_semantics": ["categorical", "categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["angle", "radius", "value"],
        "scoring_hints": {"multi_categorical_bonus": 10},
    },
    # ── Graph / Network ───────────────────────────────────────────────────────
    "network_graph": {
        "id": "network_graph",
        "echarts_type": "graph",
        "required_semantics": ["flow_source", "flow_target"],
        "optional_semantics": ["numeric"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": True,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["source", "target", "value"],
        "scoring_hints": {"flow_bonus": 30},
    },
    "network_diagram": {
        "id": "network_diagram",
        "echarts_type": "graph",
        "required_semantics": ["flow_source", "flow_target"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": True,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["source", "target"],
        "scoring_hints": {"flow_bonus": 25},
    },
    # ── Tree ──────────────────────────────────────────────────────────────────
    "treemap": {
        "id": "treemap",
        "echarts_type": "treemap",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": ["categorical"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": True, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["parent", "child", "value"],
        "scoring_hints": {"hierarchy_bonus": 25, "category_metric_bonus": 10},
    },
    "partition_map": {
        "id": "partition_map",
        "echarts_type": "treemap",
        "required_semantics": ["categorical"],
        "optional_semantics": ["numeric"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": True, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["parent", "child"],
        "scoring_hints": {"hierarchy_bonus": 20},
    },
    "tree_chart": {
        "id": "tree_chart",
        "echarts_type": "tree",
        "required_semantics": ["categorical"],
        "optional_semantics": ["categorical"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": False, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": True, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["parent", "child"],
        "scoring_hints": {"hierarchy_bonus": 20},
    },
    # ── Sunburst ──────────────────────────────────────────────────────────────
    "sunburst": {
        "id": "sunburst",
        "echarts_type": "sunburst",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": ["categorical"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": True, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["parent", "child", "value"],
        "scoring_hints": {"hierarchy_bonus": 25},
    },
    # ── Calendar ──────────────────────────────────────────────────────────────
    "calendar_chart": {
        "id": "calendar_chart",
        "echarts_type": "heatmap",
        "required_semantics": ["datetime", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": 2,
        "supports": {"numeric": True, "categorical": False, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["date", "value"],
        "scoring_hints": {"time_series_bonus": 20},
    },
    # ── Matrix ────────────────────────────────────────────────────────────────
    "correlation_matrix": {
        "id": "correlation_matrix",
        "echarts_type": "heatmap",
        "required_semantics": ["numeric", "numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["dimensions"],
        "scoring_hints": {"many_numeric_bonus": 20},
    },
    # ── Chord ─────────────────────────────────────────────────────────────────
    "chord_diagram": {
        "id": "chord_diagram",
        "echarts_type": "graph",
        "required_semantics": ["flow_source", "flow_target", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": True,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["source", "target", "value"],
        "scoring_hints": {"flow_bonus": 25},
    },
    # ── Parallel ──────────────────────────────────────────────────────────────
    "parallel_coordinates": {
        "id": "parallel_coordinates",
        "echarts_type": "parallel",
        "required_semantics": ["numeric", "numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["dimensions"],
        "scoring_hints": {"many_numeric_bonus": 20},
    },
    # ── Sankey ────────────────────────────────────────────────────────────────
    "sankey": {
        "id": "sankey",
        "echarts_type": "sankey",
        "required_semantics": ["flow_source", "flow_target", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": True,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["source", "target", "value"],
        "scoring_hints": {"flow_bonus": 35},
    },
    # ── Funnel ────────────────────────────────────────────────────────────────
    "funnel": {
        "id": "funnel",
        "echarts_type": "funnel",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": 2,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 10,
        "mapping_keys": ["stage", "value"],
        "scoring_hints": {"funnel_bonus": 20, "category_metric_bonus": 10},
    },
    # ── Gauge ─────────────────────────────────────────────────────────────────
    "gauge": {
        "id": "gauge",
        "echarts_type": "gauge",
        "required_semantics": ["numeric"],
        "optional_semantics": ["numeric"],
        "min_cols": 1, "max_cols": 2,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["value", "max"],
        "scoring_hints": {"single_numeric_bonus": 15},
    },
    # ── Theme River ───────────────────────────────────────────────────────────
    "theme_river": {
        "id": "theme_river",
        "echarts_type": "themeRiver",
        "required_semantics": ["datetime", "categorical", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": 10,
        "mapping_keys": ["date", "category", "value"],
        "scoring_hints": {"time_series_bonus": 15, "category_metric_bonus": 10},
    },
    # ── Table ─────────────────────────────────────────────────────────────────
    "table": {
        "id": "table",
        "echarts_type": "table",
        "required_semantics": [],
        "optional_semantics": [],
        "min_cols": 1, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": True},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["columns"],
        "scoring_hints": {"base_score": 40},
    },
    "pivot_table": {
        "id": "pivot_table",
        "echarts_type": "table",
        "required_semantics": ["categorical", "numeric"],
        "optional_semantics": ["categorical"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": True, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["rows", "columns", "values"],
        "scoring_hints": {"multi_categorical_bonus": 10},
    },
    # ── KPI ───────────────────────────────────────────────────────────────────
    "kpi": {
        "id": "kpi",
        "echarts_type": "kpi",
        "required_semantics": ["numeric"],
        "optional_semantics": ["numeric"],
        "min_cols": 1, "max_cols": 3,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["value", "label"],
        "scoring_hints": {"single_numeric_bonus": 15},
    },
    "big_number": {
        "id": "big_number",
        "echarts_type": "kpi",
        "required_semantics": ["numeric"],
        "optional_semantics": ["numeric"],
        "min_cols": 1, "max_cols": 3,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["value"],
        "scoring_hints": {"single_numeric_bonus": 10},
    },
    "big_number_total": {
        "id": "big_number_total",
        "echarts_type": "kpi",
        "required_semantics": ["numeric"],
        "optional_semantics": [],
        "min_cols": 1, "max_cols": 2,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["value"],
        "scoring_hints": {"single_numeric_bonus": 10},
    },
    # ── WebGL / Large Scale ───────────────────────────────────────────────────
    "scatter_gl": {
        "id": "scatter_gl",
        "echarts_type": "scatterGL",
        "required_semantics": ["numeric", "numeric"],
        "optional_semantics": ["categorical", "numeric"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": True, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": True,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y"],
        "scoring_hints": {"large_dataset_bonus": 25, "two_numeric_bonus": 10},
        "min_rows_recommended": 10000,
    },
    "lines_gl": {
        "id": "lines_gl",
        "echarts_type": "linesGL",
        "required_semantics": ["numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": True,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y"],
        "scoring_hints": {"large_dataset_bonus": 20},
        "min_rows_recommended": 10000,
    },
    "flow_gl_vector_field": {
        "id": "flow_gl_vector_field",
        "echarts_type": "custom",
        "required_semantics": ["numeric", "numeric", "numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 4, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": True,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y", "dx", "dy"],
        "scoring_hints": {"large_dataset_bonus": 15},
        "min_rows_recommended": 1000,
    },
    "graph_gl": {
        "id": "graph_gl",
        "echarts_type": "graphGL",
        "required_semantics": ["flow_source", "flow_target"],
        "optional_semantics": ["numeric"],
        "min_cols": 2, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": False, "requires_flow": True,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": True,
        "max_categories_ideal": None,
        "mapping_keys": ["source", "target"],
        "scoring_hints": {"flow_bonus": 20, "large_dataset_bonus": 20},
        "min_rows_recommended": 10000,
    },
    # ── 3D Surface ────────────────────────────────────────────────────────────
    "3d_surface_plot": {
        "id": "3d_surface_plot",
        "echarts_type": "surface",
        "required_semantics": ["numeric", "numeric", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": 3,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": False},
        "requires_geo": False, "requires_3d": True, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["x", "y", "z"],
        "scoring_hints": {"three_numeric_bonus": 20},
    },
    # ── 3D Hexagon Map ────────────────────────────────────────────────────────
    "3d_hexagon_map": {
        "id": "3d_hexagon_map",
        "echarts_type": "custom",
        "required_semantics": ["geo_lon", "geo_lat", "numeric"],
        "optional_semantics": [],
        "min_cols": 3, "max_cols": None,
        "supports": {"numeric": True, "categorical": False, "datetime": False, "geographic": True},
        "requires_geo": True, "requires_3d": True, "requires_flow": False,
        "requires_hierarchy": False, "requires_ohlc": False, "webgl": False,
        "max_categories_ideal": None,
        "mapping_keys": ["longitude", "latitude", "value"],
        "scoring_hints": {"geo_latlon_bonus": 20},
    },
}

# ---------------------------------------------------------------------------
# Full chart catalog entries from Excel
# ---------------------------------------------------------------------------
EXCEL_CHARTS = [
    # Bar Charts sheet
    {"name": "Bar", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "bar",
     "uses": "Compare values across discrete categories or rank categories by magnitude.",
     "dataset": "Category + numeric value; optional series.",
     "example": "Monthly sales by product: A $120K, B $95K, C $80K."},
    {"name": "Waterfall Chart", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "waterfall_chart",
     "uses": "Show how sequential positive and negative changes produce a final total.",
     "dataset": "Ordered step/category + numeric change; optional subtotal/total.",
     "example": "Revenue bridge: Opening $500K + Sales $120K - Returns $30K = Closing $570K."},
    {"name": "Polar Bar", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "polar_bar",
     "uses": "Compare magnitudes around a circular/polar axis.",
     "dataset": "Category + numeric magnitude; optional series.",
     "example": "Sales by weekday shown radially."},
    {"name": "Bar Chart Race", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "bar_chart_race",
     "uses": "Show how category rankings change over time through animation.",
     "dataset": "Time + category + numeric value.",
     "example": "Top 10 countries by population for each year."},
    {"name": "Range Bar Chart", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "range_bar_chart",
     "uses": "Display a minimum-to-maximum interval for each category.",
     "dataset": "Category + low/min + high/max.",
     "example": "Project duration: Design 5–12 days, Development 10–25 days."},
    {"name": "Horizontal Waterfall Chart", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "horizontal_waterfall_chart",
     "uses": "Show sequential increases and decreases in a horizontal layout.",
     "dataset": "Ordered category + numeric change; optional totals.",
     "example": "Cash-flow bridge."},
    {"name": "Circular Bar Chart", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "circular_bar_chart",
     "uses": "Compare category magnitudes in a circular layout.",
     "dataset": "Category + numeric magnitude.",
     "example": "Revenue by region arranged around a circle."},
    {"name": "Stacked Bar Chart", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "stacked_bar_chart",
     "uses": "Show totals and composition across categories.",
     "dataset": "Category + numeric value + stack/series.",
     "example": "Quarterly revenue split by Product, Services, Support."},
    {"name": "3D Bar Chart", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "3d_bar_chart",
     "uses": "Compare values using three-dimensional bars across dimensions.",
     "dataset": "Category/series + numeric value; optional second category.",
     "example": "Sales by region and quarter."},
    {"name": "Progress Bar", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "progress_bar",
     "uses": "Show current progress toward a target or maximum.",
     "dataset": "Current value + target/max; optional label/category.",
     "example": "Project completion: 72% complete."},
    {"name": "Bar with Line", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "bar_with_line",
     "uses": "Compare a bar metric with a line metric, often using different scales.",
     "dataset": "Category/time + bar measure + line measure.",
     "example": "Monthly sales bars with conversion-rate line."},
    {"name": "Error Bar Chart", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "error_bar_chart",
     "uses": "Show a central estimate with uncertainty or variability.",
     "dataset": "Category + central value + error or low/high bounds.",
     "example": "Average response time 220 ms with confidence range."},
    {"name": "Stacked Horizontal Bar", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "stacked_horizontal_bar",
     "uses": "Compare totals and composition with horizontal stacked bars.",
     "dataset": "Category + numeric value + stack/series.",
     "example": "Support tickets by team."},
    {"name": "Horizontal Bar", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "horizontal_bar",
     "uses": "Compare categories when labels are long or horizontal layout improves readability.",
     "dataset": "Category + numeric value; optional series.",
     "example": "Top customer issues with long labels."},
    {"name": "100% Stacked Bar", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "100_stacked_bar",
     "uses": "Compare proportional composition where each category totals 100%.",
     "dataset": "Category + numeric value + stack/series.",
     "example": "Market share by region."},
    {"name": "100% Stacked Horizontal Bar", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "100_stacked_horizontal_bar",
     "uses": "Compare proportional composition horizontally.",
     "dataset": "Category + numeric value + stack/series.",
     "example": "Employee distribution by department."},
    {"name": "Pictorial (Vector Icon) Bar", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "pictorial_bar",
     "uses": "Represent quantities using repeated or scaled icons.",
     "dataset": "Category + numeric value; icon/vector definition.",
     "example": "Devices by type represented with icons."},
    {"name": "Polar End-Angle Arc Bar", "category": "Bar Charts", "sheet": "Bar Charts", "meta_id": "polar_end_angle_arc_bar",
     "uses": "Compare magnitudes using radial bars whose end angle represents the value.",
     "dataset": "Category + numeric value; optional maximum/reference.",
     "example": "Energy consumption by building."},
    # Line Charts
    {"name": "Line", "category": "Line Charts", "sheet": "Line Charts", "meta_id": "line",
     "uses": "Show trends and changes across an ordered dimension, especially time.",
     "dataset": "Time/category + numeric value; optional multiple series.",
     "example": "Monthly revenue Jan–Jun."},
    {"name": "Area", "category": "Line Charts", "sheet": "Line Charts", "meta_id": "area",
     "uses": "Show trends while emphasizing magnitude through filled area.",
     "dataset": "Ordered dimension + numeric value; optional series.",
     "example": "Daily website visits across a month."},
    {"name": "Stepped Line", "category": "Line Charts", "sheet": "Line Charts", "meta_id": "stepped_line",
     "uses": "Show values that change in discrete steps rather than continuously.",
     "dataset": "Ordered dimension + numeric value.",
     "example": "Subscription price changes."},
    {"name": "Smooth Line", "category": "Line Charts", "sheet": "Line Charts", "meta_id": "smooth_line",
     "uses": "Show an overall continuous trend using a smoothed curve.",
     "dataset": "Ordered dimension + numeric value.",
     "example": "Temperature readings across a day."},
    {"name": "Polar Line", "category": "Line Charts", "sheet": "Line Charts", "meta_id": "polar_line",
     "uses": "Show cyclical or directional trends around a polar coordinate system.",
     "dataset": "Angular/category dimension + numeric value.",
     "example": "Average wind speed by compass direction."},
    {"name": "Stacked Area", "category": "Line Charts", "sheet": "Line Charts", "meta_id": "stacked_area",
     "uses": "Show how multiple series contribute to a total over an ordered axis.",
     "dataset": "Time/category + numeric value + series.",
     "example": "Monthly energy consumption stacked by Lighting, HVAC, Equipment."},
    {"name": "3D Line Chart", "category": "Line Charts", "sheet": "Line Charts", "meta_id": "3d_line_chart",
     "uses": "Show trends across three dimensions using connected lines.",
     "dataset": "X + Y dimension + numeric/Z value; optional series.",
     "example": "Temperature trajectory by day and altitude."},
    {"name": "Stacked Line Chart", "category": "Line Charts", "sheet": "Line Charts", "meta_id": "stacked_line_chart",
     "uses": "Show cumulative contributions of multiple series across an ordered axis.",
     "dataset": "Ordered dimension + value + series.",
     "example": "Support volume over months."},
    {"name": "Bump Chart (Ranking)", "category": "Line Charts", "sheet": "Line Charts", "meta_id": "bump_chart",
     "uses": "Show how category rankings change across time.",
     "dataset": "Time + category + rank or score.",
     "example": "Product ranking across Q1–Q4."},
    {"name": "Confidence Band Line", "category": "Line Charts", "sheet": "Line Charts", "meta_id": "confidence_band_line",
     "uses": "Show a central trend with an uncertainty/confidence range.",
     "dataset": "Ordered dimension + central value + lower/upper bounds.",
     "example": "Forecast demand with 95% confidence bounds."},
    {"name": "Function Plot (Math Equation)", "category": "Line Charts", "sheet": "Line Charts", "meta_id": "function_plot",
     "uses": "Plot a mathematical function over a defined input range.",
     "dataset": "X values or equation + calculated Y values.",
     "example": "Plot y = x² for x from -5 to 5."},
    {"name": "Multi-X Axis Line", "category": "Line Charts", "sheet": "Line Charts", "meta_id": "multi_x_axis_line",
     "uses": "Compare series that use different X-axis scales or dimensions.",
     "dataset": "One or more X dimensions + numeric Y values.",
     "example": "Compare sales by calendar month with fiscal period."},
    # Pie Charts
    {"name": "Pie", "category": "Pie Charts", "sheet": "Pie  Charts", "meta_id": "pie",
     "uses": "Show category contributions to a meaningful whole.",
     "dataset": "Category + numeric value that forms a total.",
     "example": "Revenue mix by channel."},
    {"name": "Donut", "category": "Pie Charts", "sheet": "Pie  Charts", "meta_id": "donut",
     "uses": "Show part-to-whole composition with a center area for a total/KPI.",
     "dataset": "Category + numeric value.",
     "example": "Expense mix with total spend in center."},
    {"name": "Nightingale Rose", "category": "Pie Charts", "sheet": "Pie  Charts", "meta_id": "nightingale_rose",
     "uses": "Compare category magnitudes using radial sectors with varying radius.",
     "dataset": "Category + numeric value.",
     "example": "Customer complaints by type."},
    # Scatter
    {"name": "Scatter", "category": "Scatter Charts", "sheet": "Scatter Charts", "meta_id": "scatter",
     "uses": "Show relationships, correlation, clustering, and outliers between numerical variables.",
     "dataset": "Numeric X + numeric Y per observation; optional category.",
     "example": "Advertising spend vs revenue."},
    {"name": "Bubble", "category": "Scatter Charts", "sheet": "Scatter Charts", "meta_id": "bubble",
     "uses": "Show relationships while using bubble size for a third variable.",
     "dataset": "Numeric X + numeric Y + numeric size; optional category/color.",
     "example": "Country GDP vs population, bubble = exports."},
    {"name": "Effect Scatter", "category": "Scatter Charts", "sheet": "Scatter Charts", "meta_id": "effect_scatter",
     "uses": "Show relationships/effects while emphasizing notable observations.",
     "dataset": "Numeric X + numeric Y; optional effect size/category/significance.",
     "example": "Treatment effect vs baseline score."},
    {"name": "Scatter Matrix", "category": "Scatter Charts", "sheet": "Scatter Charts", "meta_id": "scatter_matrix",
     "uses": "Show pairwise relationships between multiple numerical variables.",
     "dataset": "Multiple numerical columns with one row per observation.",
     "example": "Compare Age, Income, Spend, Tenure pairwise."},
    {"name": "3D Scatter Plot", "category": "Scatter Charts", "sheet": "Scatter Charts", "meta_id": "3d_scatter_plot",
     "uses": "Show relationships among three numerical variables.",
     "dataset": "Numeric X + Y + Z per observation; optional category.",
     "example": "Plot height, weight, and age."},
    # Map
    {"name": "3D Arc Map", "category": "Map", "sheet": "Map", "meta_id": "3d_arc_map",
     "uses": "Show geographic routes or connections as elevated 3D arcs.",
     "dataset": "Origin longitude/latitude + destination longitude/latitude + optional flow value.",
     "example": "Flight routes between cities."},
    {"name": "3D Grid Map", "category": "Map", "sheet": "Map", "meta_id": "3d_grid_map",
     "uses": "Represent geographic or spatial data on a 3D grid.",
     "dataset": "Grid X/Y or longitude/latitude + numeric value; optional category.",
     "example": "Retail footfall across a mall grid."},
    {"name": "Screen Grid Map", "category": "Map", "sheet": "Map", "meta_id": "screen_grid_map",
     "uses": "Display aggregated spatial information using a grid/screen-cell representation.",
     "dataset": "Grid cell coordinates + numeric value; optional category.",
     "example": "Network latency by monitoring tile."},
    {"name": "Heatmap (Geographic)", "category": "Map", "sheet": "Map", "meta_id": "heatmap_geo",
     "uses": "Show geographic or spatial intensity using color.",
     "dataset": "X/Y coordinates or geographic grid + numeric intensity.",
     "example": "Customer service requests across city locations."},
    {"name": "3D Scatter Map", "category": "Map", "sheet": "Map", "meta_id": "3d_scatter_map",
     "uses": "Plot geographic points in 3D with an additional height, size, or color dimension.",
     "dataset": "Longitude + latitude + numeric height/value; optional size/category.",
     "example": "Store locations with sales revenue as point height."},
    {"name": "Contour Map", "category": "Map", "sheet": "Map", "meta_id": "contour_map",
     "uses": "Show continuous spatial values using contour lines or filled contour regions.",
     "dataset": "X/Y spatial grid + numeric Z/value.",
     "example": "Temperature across a geographic region."},
    {"name": "Deck Multi-layer Map", "category": "Map", "sheet": "Map", "meta_id": "deck_multilayer_map",
     "uses": "Combine multiple geographic layers such as points, lines, polygons, grids, and routes.",
     "dataset": "Layer-specific geographic points, lines, polygons, grids, and optional metrics.",
     "example": "City operations map with multiple overlays."},
    {"name": "Geographic Region Map", "category": "Map", "sheet": "Map", "meta_id": "geographic_region_map",
     "uses": "Compare values across geographic regions such as countries, states, or districts.",
     "dataset": "Region name/code + numeric value; optional category.",
     "example": "Sales by Indian state."},
    {"name": "Geo Connection Lines", "category": "Map", "sheet": "Map", "meta_id": "geo_connection_lines",
     "uses": "Show connections, routes, or flows between geographic locations.",
     "dataset": "Source longitude/latitude + target longitude/latitude + optional flow/value.",
     "example": "Air-cargo connections between cities."},
    {"name": "3D Geographic Globe", "category": "Map", "sheet": "Map", "meta_id": "3d_geographic_globe",
     "uses": "Display geographic data on a three-dimensional globe.",
     "dataset": "Longitude/latitude + optional value, region, point, or flow data.",
     "example": "Global sales distribution by country."},
    {"name": "3D Geo Arcs", "category": "Map", "sheet": "Map", "meta_id": "3d_geo_arcs",
     "uses": "Show flows or connections between geographic locations using 3D arcs.",
     "dataset": "Origin/destination longitude/latitude + flow value.",
     "example": "Global shipment routes."},
    # Candlestick
    {"name": "Candlestick Chart", "category": "Candlestick Charts", "sheet": "Candlestick Charts", "meta_id": "candlestick_chart",
     "uses": "Show open, high, low, and close price movement over time.",
     "dataset": "Time + open + high + low + close; optional volume.",
     "example": "Daily stock price OHLC."},
    # Radar
    {"name": "Radar", "category": "Radar Charts", "sheet": "Radar Charts", "meta_id": "radar",
     "uses": "Compare multiple quantitative dimensions across one or more profiles.",
     "dataset": "Category/profile + multiple numeric dimensions.",
     "example": "Compare products across Price, Quality, Speed, Reliability, Support."},
    # Box Plot
    {"name": "Box Plot", "category": "Box Plot Charts", "sheet": "Box plot charts ", "meta_id": "box_plot",
     "uses": "Show distribution, quartiles, median, spread, and outliers.",
     "dataset": "Raw numeric observations by category OR min/Q1/median/Q3/max.",
     "example": "Compare delivery times for Standard, Express, Same-Day."},
    # Custom
    {"name": "Bullet Chart", "category": "Custom Charts", "sheet": "Custom Charts", "meta_id": "bullet_chart",
     "uses": "Compare actual value against a target and qualitative performance ranges.",
     "dataset": "Actual value + target; optional range thresholds.",
     "example": "Sales target $1M, actual $820K."},
    # Heatmap sheet
    {"name": "Heatmap", "category": "Heatmap", "sheet": "Heatmap", "meta_id": "heatmap",
     "uses": "Show value intensity across two dimensions using color.",
     "dataset": "X category/time + Y category + numeric value.",
     "example": "Website traffic by weekday and hour."},
    {"name": "Calendar Heatmap", "category": "Heatmap", "sheet": "Heatmap", "meta_id": "calendar_heatmap",
     "uses": "Show daily values across calendar dates using color intensity.",
     "dataset": "Date + numeric value.",
     "example": "GitHub-style contribution activity."},
    {"name": "Polar Heatmap", "category": "Heatmap", "sheet": "Heatmap", "meta_id": "polar_heatmap",
     "uses": "Show cyclical or directional values in polar coordinates using color.",
     "dataset": "Angle/category + radial category + numeric value.",
     "example": "Hourly activity by day-of-week as circular heatmap."},
    # Graph
    {"name": "Network Graph", "category": "Graph", "sheet": "Graph", "meta_id": "network_graph",
     "uses": "Show entities and relationships as nodes and links.",
     "dataset": "Node ID/label + edge source/target; optional weights.",
     "example": "Employee collaboration network."},
    {"name": "Network Diagram", "category": "Graph", "sheet": "Graph", "meta_id": "network_diagram",
     "uses": "Show structured relationships, flows, dependencies, or system architecture.",
     "dataset": "Node/entity + source-target relationships; optional hierarchy.",
     "example": "Application architecture: Frontend → API → Service → Database."},
    # Tree
    {"name": "Treemap (Tree Sheet)", "category": "Tree", "sheet": "Tree", "meta_id": "treemap",
     "uses": "Show hierarchical data using nested rectangles sized by value.",
     "dataset": "Hierarchical parent/child data + numeric value.",
     "example": "Company budget hierarchy."},
    {"name": "Partition Map", "category": "Tree", "sheet": "Tree", "meta_id": "partition_map",
     "uses": "Show hierarchical structure using proportional spatial partitions.",
     "dataset": "Hierarchical parent/child data + optional numeric value.",
     "example": "Product catalog hierarchy."},
    {"name": "Tree Chart", "category": "Tree", "sheet": "Tree", "meta_id": "tree_chart",
     "uses": "Show parent-child hierarchy and relationships.",
     "dataset": "Node ID/name + parent-child structure.",
     "example": "Organization chart."},
    # Treemap sheet (deduplicate)
    {"name": "Treemap", "category": "Treemap", "sheet": "Treemap", "meta_id": "treemap",
     "uses": "Compare hierarchical categories and subcategories using nested proportional rectangles.",
     "dataset": "Hierarchical data + numeric value.",
     "example": "Disk usage: Drive → Folder → Subfolder, size = GB."},
    # Sunburst
    {"name": "Sunburst", "category": "Sunburst", "sheet": "Sunburst", "meta_id": "sunburst",
     "uses": "Explore multi-level hierarchy using concentric rings.",
     "dataset": "Hierarchical parent/child data + numeric value.",
     "example": "Sales hierarchy: Region → Country → Product → SKU."},
    # Calendar
    {"name": "Calendar Heatmap (Calendar Sheet)", "category": "Calendar", "sheet": "Calendar", "meta_id": "calendar_chart",
     "uses": "Track daily values and identify patterns or seasonality across calendar periods.",
     "dataset": "Date + numeric value.",
     "example": "Daily orders for 2026."},
    # Matrix
    {"name": "Scatter Matrix (Matrix Sheet)", "category": "Matrix", "sheet": "Matrix", "meta_id": "scatter_matrix",
     "uses": "Explore pairwise relationships among multiple numerical variables.",
     "dataset": "Multiple numeric fields per observation.",
     "example": "Pairwise analysis of Age, Salary, Spend, Tenure."},
    {"name": "Correlation Matrix", "category": "Matrix", "sheet": "Matrix", "meta_id": "correlation_matrix",
     "uses": "Show strength and direction of relationships between numerical variables.",
     "dataset": "Numerical columns; correlation coefficients may be precomputed.",
     "example": "Correlation among Revenue, Orders, AOV, Marketing Spend."},
    # Chord
    {"name": "Chord Diagram", "category": "Chord", "sheet": "Chord", "meta_id": "chord_diagram",
     "uses": "Show many-to-many relationships or flows between entities.",
     "dataset": "Node list + source-target-value relationships.",
     "example": "Inter-department transfers."},
    # Parallel
    {"name": "Parallel Coordinates", "category": "Parallel Charts", "sheet": "Parallel charts", "meta_id": "parallel_coordinates",
     "uses": "Compare many variables across observations in a high-dimensional dataset.",
     "dataset": "One row per observation + multiple numerical dimensions.",
     "example": "Compare cars across MPG, horsepower, weight, acceleration, price."},
    # Sankey
    {"name": "Sankey", "category": "Sankey Charts", "sheet": "Sankey Charts", "meta_id": "sankey",
     "uses": "Show quantities flowing between stages/entities, with link width representing magnitude.",
     "dataset": "Nodes + source-target-value links.",
     "example": "Website flow: Landing → Product → Cart → Checkout → Purchase."},
    # Funnel
    {"name": "Funnel", "category": "Funnel Charts", "sheet": "Funnel Charts", "meta_id": "funnel",
     "uses": "Show progressive reduction through sequential stages.",
     "dataset": "Ordered stage + numeric value.",
     "example": "Sales funnel: Leads → Qualified → Proposals → Won."},
    # Gauge
    {"name": "Gauge", "category": "Gauge", "sheet": "Gauge", "meta_id": "gauge",
     "uses": "Display a single value against a defined scale or target range.",
     "dataset": "Single numeric value + min/max; optional thresholds.",
     "example": "Server CPU utilization at 72%."},
    # Theme River
    {"name": "Theme River", "category": "Theme River", "sheet": "Theme River", "meta_id": "theme_river",
     "uses": "Show how multiple categories change in volume over time.",
     "dataset": "Time + category/theme + numeric value.",
     "example": "News topic volume over months."},
    # Table
    {"name": "Table", "category": "Table", "sheet": "Table", "meta_id": "table",
     "uses": "Display detailed structured records for inspection, sorting, filtering, and comparison.",
     "dataset": "Rows/records + named columns of relevant types.",
     "example": "Order table: Order ID, Customer, Date, Product, Quantity, Revenue."},
    {"name": "Pivot Table", "category": "Table", "sheet": "Table", "meta_id": "pivot_table",
     "uses": "Summarize and aggregate large datasets by dimensions and measures.",
     "dataset": "Dimension fields + numeric measures + aggregation definition.",
     "example": "Sales summarized by Region × Quarter."},
    # KPI
    {"name": "KPI", "category": "KPI", "sheet": "KPI", "meta_id": "kpi",
     "uses": "Display a key performance indicator as a prominent single value.",
     "dataset": "Single metric value + optional target/comparison.",
     "example": "Monthly recurring revenue KPI: $80.7M."},
    {"name": "Big Number", "category": "KPI", "sheet": "KPI", "meta_id": "big_number",
     "uses": "Highlight an important current metric, often with change/trend context.",
     "dataset": "Current value + optional previous value or percentage change.",
     "example": "Revenue $215M with +7.0% week-over-week."},
    {"name": "Big Number Total", "category": "KPI", "sheet": "KPI", "meta_id": "big_number_total",
     "uses": "Prominently display an aggregate total.",
     "dataset": "Aggregated numeric total; optional label/period.",
     "example": "Total transactions: 80.7M."},
    # 3D Charts sheet
    {"name": "3D Hexagon Map", "category": "3D Charts", "sheet": "3D Charts", "meta_id": "3d_hexagon_map",
     "uses": "Show spatial/geographic density using hexagonal cells with height or intensity.",
     "dataset": "Longitude + latitude + numeric value; optional category.",
     "example": "Customer density by city using hexagons."},
    {"name": "Scatter GL (WebGL)", "category": "3D Charts", "sheet": "3D Charts", "meta_id": "scatter_gl",
     "uses": "Render very large scatter datasets efficiently with WebGL.",
     "dataset": "Large set of X/Y numeric points; optional category/size.",
     "example": "Plot 500,000 sensor observations."},
    {"name": "Lines GL (WebGL)", "category": "3D Charts", "sheet": "3D Charts", "meta_id": "lines_gl",
     "uses": "Render large numbers of lines efficiently with WebGL.",
     "dataset": "Large set of line/trajectory coordinates.",
     "example": "Render 100,000 vehicle GPS trajectories."},
    {"name": "Flow GL Vector Field", "category": "3D Charts", "sheet": "3D Charts", "meta_id": "flow_gl_vector_field",
     "uses": "Visualize directional flow fields at scale.",
     "dataset": "Grid coordinates + vector direction/magnitude.",
     "example": "Wind direction and speed across a weather grid."},
    {"name": "Graph GL (WebGL)", "category": "3D Charts", "sheet": "3D Charts", "meta_id": "graph_gl",
     "uses": "Render large network graphs efficiently with WebGL.",
     "dataset": "Large node list + source/target edge list; optional weights/categories.",
     "example": "Dependency network with 50,000 nodes."},
    {"name": "3D Surface Plot", "category": "3D Charts", "sheet": "3D Charts", "meta_id": "3d_surface_plot",
     "uses": "Show a continuous surface where height represents a third value.",
     "dataset": "X + Y grid coordinates + Z/value.",
     "example": "Plot z = sin(x) × cos(y)."},
]


def build_catalog():
    """Combine EXCEL_CHARTS with CHART_META to produce the full catalog."""
    seen_ids = set()
    catalog = []
    for entry in EXCEL_CHARTS:
        mid = entry["meta_id"]
        if mid in seen_ids:
            continue  # deduplicate
        seen_ids.add(mid)
        meta = CHART_META.get(mid, {})
        record = {
            "id": mid,
            "name": entry["name"],
            "category": entry["category"],
            "sheet": entry["sheet"],
            "description": entry["uses"],
            "dataset_required": entry["dataset"],
            "example": entry["example"],
            "echarts_type": meta.get("echarts_type", "custom"),
            "required_semantics": meta.get("required_semantics", []),
            "optional_semantics": meta.get("optional_semantics", []),
            "min_cols": meta.get("min_cols", 1),
            "max_cols": meta.get("max_cols"),
            "supports": meta.get("supports", {}),
            "requires_geo": meta.get("requires_geo", False),
            "requires_3d": meta.get("requires_3d", False),
            "requires_flow": meta.get("requires_flow", False),
            "requires_hierarchy": meta.get("requires_hierarchy", False),
            "requires_ohlc": meta.get("requires_ohlc", False),
            "webgl": meta.get("webgl", False),
            "max_categories_ideal": meta.get("max_categories_ideal"),
            "mapping_keys": meta.get("mapping_keys", []),
            "scoring_hints": meta.get("scoring_hints", {}),
            "min_rows_recommended": meta.get("min_rows_recommended", 1),
        }
        catalog.append(record)
    return catalog


if __name__ == "__main__":
    catalog = build_catalog()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        json.dump({"version": "1.0", "total": len(catalog), "charts": catalog}, f, indent=2)
    print(f"✅ Chart catalog built: {len(catalog)} unique charts → {OUTPUT_PATH}")
